In [ ]:
# importng necessary libraries.
import os
import sys
import pandas as pd
import matplotlib.pyplot as plt
sys.path.appen)d(os.path.abspath("..")

from constants import (
    NSDCC_CLEAN,
    COUNTY_PROF,
    TIER_TS,
    NSDCC_COUNTY_COL,
    NSDCC_PERIOD_COL
)

from src.feature_engineering import (    
    build_county_profiles,
    build_tier_timeseries
)

In [33]:
import os
import sys
import pandas as pd
import matplotlib.pyplot as plt

sys.path.append(
    os.path.abspath("..")
)
from src.feature_engineering import (
    run_feature_engineering,
    build_county_profiles,
    build_tier_timeseries
)
from constants import (
    NSDCC_CLEAN,
    PROCESSED_DIR,
    COUNTY_PROF,
    TIER_TS,
    NSDCC_COUNTY_COL,
    NSDCC_PERIOD_COL
)

ImportError: cannot import name 'run_feature_engineering' from 'src.feature_engineering' (c:\Users\Admin\documents\flatiron\Phase5project\Phase-5-HIV-Care-Gap-AI\src\feature_engineering.py)

In [23]:
NSDCC_CLEAN = pd.read_csv(NSDCC_CLEAN)
NSDCC_CLEAN.head()

,period,county,MOH 731_HIV_TB_OnART_15-19_(F)_HV03-24,MOH 731_HIV_TB_OnART_15-19_(M)_HV03-23,MOH 731_HIV_TB_OnART_20-24_(F)_HV03-26,MOH 731_HIV_TB_OnART_20-24_(M)_HV03-25,MOH 731_HIV_TB_OnART_25+_(F)_HV03-28,MOH 731_HIV_TB_OnART_25+_(M)_HV03-27,adults_on_art,art_total_males,...,Actively on Treatment by the Beginning of 2025 female adult,iit_female,Actively on Treatment by the Beginning of 2025 Male,iit_male,adults_on_treatment,iit_count,iit_rate_pct,iit_rate_children_pct,iit_rate_male_pct,iit_rate_female_pct
0,2025,Baringo,82,70,164,92,3629,1701,5738,1863,...,524.214286,80.357143,280.00,42.714286,804.214286,123.071429,0.1530,0.131,0.153,0.153
1,2025,Bomet,234,160,416,175,7745,3616,12346,3951,...,524.214286,80.357143,280.00,42.714286,804.214286,123.071429,0.1530,0.131,0.153,0.153
2,2025,Bungoma,591,450,1235,400,20203,7717,30596,8567,...,932.500000,85.250000,425.75,36.250000,1358.250000,121.500000,0.0895,0.070,0.085,0.091
3,2025,Busia,543,467,940,425,23538,11203,37116,12095,...,932.500000,85.250000,425.75,36.250000,1358.250000,121.500000,0.0895,0.070,0.085,0.091
4,2025,Elgeyo Marakwet,83,68,149,55,3196,1368,4919,1491,...,524.214286,80.357143,280.00,42.714286,804.214286,123.071429,0.1530,0.131,0.153,0.153

In [24]:
#checking columns to confirm if these exists: county, period, iit_rate, vls_rate_adult
NSDCC_CLEAN.columns

Index(['period', 'county', 'MOH 731_HIV_TB_OnART_15-19_(F)_HV03-24',
       'MOH 731_HIV_TB_OnART_15-19_(M)_HV03-23',
       'MOH 731_HIV_TB_OnART_20-24_(F)_HV03-26',
       'MOH 731_HIV_TB_OnART_20-24_(M)_HV03-25',
       'MOH 731_HIV_TB_OnART_25+_(F)_HV03-28',
       'MOH 731_HIV_TB_OnART_25+_(M)_HV03-27', 'adults_on_art',
       'art_total_males', 'art_total_females',
       'MOH 731_HTS_Tests _(F) (Including PMTCT)_ HV01-02',
       'MOH 731_HTS_Tests _(M)_ HV01-01', 'hts_tested', 'hts_tested_males',
       'hts_tested_females', 'vlt_valid_under15', 'vls_suppressed_under15',
       'vlt_valid_male_15plus', 'vls_suppressed_male_15plus',
       'vlt_valid_female_15plus', 'vls_suppressed_female_15plus',
       'vls_rate_male15plus', 'vls_rate_female15plus', 'vls_rate_under15',
       'vls_rate_adult',
       'Actively on Treatment by the Beginning of 2025 Children',
       'iit_children',
       'Actively on Treatment by the Beginning of 2025 female adult',
       'iit_female', 'Actively on Treatment by the Beginning of 2025 Male',
       'iit_male', 'adults_on_treatment', 'iit_count', 'iit_rate_pct',
       'iit_rate_children_pct', 'iit_rate_male_pct', 'iit_rate_female_pct'],
      dtype='object')

In [25]:
NSDCC_CLEAN.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 38 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   period                                                       47 non-null     int64
 1   county                                                       47 non-null     object
 2   MOH 731_HIV_TB_OnART_15-19_(F)_HV03-24                       47 non-null     int64
 3   MOH 731_HIV_TB_OnART_15-19_(M)_HV03-23                       47 non-null     int64
 4   MOH 731_HIV_TB_OnART_20-24_(F)_HV03-26                       47 non-null     int64
 5   MOH 731_HIV_TB_OnART_20-24_(M)_HV03-25                       47 non-null     int64
 6   MOH 731_HIV_TB_OnART_25+_(F)_HV03-28                         47 non-null     int64
 7   MOH 731_HIV_TB_OnART_25+_(M)_HV03-27                         47 non-null     int64
 8   adults_on_art                                                47 non-null     int64
 9   art_total_males                                              47 non-null     int64
 10  art_total_females                                            47 non-null     int64
 11  MOH 731_HTS_Tests _(F) (Including PMTCT)_ HV01-02            47 non-null     int64
 12  MOH 731_HTS_Tests _(M)_ HV01-01                              47 non-null     int64
 13  hts_tested                                                   47 non-null     int64
 14  hts_tested_males                                             47 non-null     int64
 15  hts_tested_females                                           47 non-null     int64
 16  vlt_valid_under15                                            47 non-null     int64
 17  vls_suppressed_under15                                       47 non-null     int64
 18  vlt_valid_male_15plus                                        47 non-null     int64
 19  vls_suppressed_male_15plus                                   47 non-null     float64
 20  vlt_valid_female_15plus                                      47 non-null     int64
 21  vls_suppressed_female_15plus                                 47 non-null     int64
 22  vls_rate_male15plus                                          47 non-null     float64
 23  vls_rate_female15plus                                        47 non-null     float64
 24  vls_rate_under15                                             47 non-null     float64
 25  vls_rate_adult                                               47 non-null     float64
 26  Actively on Treatment by the Beginning of 2025 Children      47 non-null     float64
 27  iit_children                                                 47 non-null     float64
 28  Actively on Treatment by the Beginning of 2025 female adult  47 non-null     float64
 29  iit_female                                                   47 non-null     float64
 30  Actively on Treatment by the Beginning of 2025 Male          47 non-null     float64
 31  iit_male                                                     47 non-null     float64
 32  adults_on_treatment                                          47 non-null     float64
 33  iit_count                                                    47 non-null     float64
 34  iit_rate_pct                                                 47 non-null     float64
 35  iit_rate_children_pct                                        47 non-null     float64
 36  iit_rate_male_pct                                            47 non-null     float64
 37  iit_rate_female_pct                                          47 non-null     float64
dtypes: float64(17), int64(20), object(1)
memory usage: 14.1+ KB

In [26]:
county_profiles = build_county_profiles(NSDCC_CLEAN)

county_profiles.head()

Saved county profiles to: c:\Users\Admin\documents\flatiron\Phase5project\Phase-5-HIV-Care-Gap-AI\data\processed\county_profiles.csv

,period,county,MOH 731_HIV_TB_OnART_15-19_(F)_HV03-24,MOH 731_HIV_TB_OnART_15-19_(M)_HV03-23,MOH 731_HIV_TB_OnART_20-24_(F)_HV03-26,MOH 731_HIV_TB_OnART_20-24_(M)_HV03-25,MOH 731_HIV_TB_OnART_25+_(F)_HV03-28,MOH 731_HIV_TB_OnART_25+_(M)_HV03-27,adults_on_art,art_total_males,...,Actively on Treatment by the Beginning of 2025 female adult,iit_female,Actively on Treatment by the Beginning of 2025 Male,iit_male,adults_on_treatment,iit_count,iit_rate_pct,iit_rate_children_pct,iit_rate_male_pct,iit_rate_female_pct
0,2025,Baringo,82,70,164,92,3629,1701,5738,1863,...,524.214286,80.357143,280.000000,42.714286,804.214286,123.071429,0.1530,0.131,0.153,0.153
1,2025,Meru,445,334,702,397,14735,6783,23396,7514,...,417.000000,38.750000,218.125000,17.625000,635.125000,56.375000,0.0888,0.071,0.081,0.093
2,2025,Migori,1595,1299,2292,790,47848,22295,76119,24384,...,1507.500000,135.333333,735.833333,69.500000,2243.333333,204.833333,0.0913,0.086,0.094,0.090
3,2025,Mombasa,541,482,1152,599,32111,15386,50271,16467,...,432.000000,40.666667,199.833333,17.833333,631.833333,58.500000,0.0926,0.161,0.089,0.094
4,2025,Murang'a,238,221,469,274,11438,5224,17864,5719,...,538.000000,51.800000,284.400000,31.000000,822.400000,82.800000,0.1007,0.085,0.109,0.096

In [28]:
tier_timeseries = build_tier_timeseries(NSDCC_CLEAN)

tier_timeseries.head()

KeyError: 'tier'

In [31]:
latest = (
    NSDCC_CLEAN.sort_values(NSDCC_PERIOD_COL)()
    .groupby(NSDCC_COUNTY_COL)
    .last()
    .reset_index()
)

plt.figure(figsize=(14, 6))

plt.hist(
    latest["care_gap_index"],
    bins=15
)

plt.xlabel("Care Gap Index")
plt.ylabel("Number of Counties")
plt.title(
    "Distribution of Care Gap Index Across Counties"
)

plt.show()

KeyError: 'Period'

In [16]:
# calculating year-over-year change for iit_rate
NSDCC_CLEAN = calculate_yoy_change(
    NSDCC_CLEAN,
    value_col="iit_rate_pct"
)

NSDCC_CLEAN.head()

,period,county,MOH 731_HIV_TB_OnART_15-19_(F)_HV03-24,MOH 731_HIV_TB_OnART_15-19_(M)_HV03-23,MOH 731_HIV_TB_OnART_20-24_(F)_HV03-26,MOH 731_HIV_TB_OnART_20-24_(M)_HV03-25,MOH 731_HIV_TB_OnART_25+_(F)_HV03-28,MOH 731_HIV_TB_OnART_25+_(M)_HV03-27,adults_on_art,art_total_males,...,Actively on Treatment by the Beginning of 2025 Male,iit_male,adults_on_treatment,iit_count,iit_rate_pct,iit_rate_children_pct,iit_rate_male_pct,iit_rate_female_pct,vls_rate_adult_yoy_change,iit_rate_pct_yoy_change
0,2025,Baringo,82,70,164,92,3629,1701,5738,1863,...,280.00,42.714286,804.214286,123.071429,0.1530,0.131,0.153,0.153,0.0,0.0
1,2025,Bomet,234,160,416,175,7745,3616,12346,3951,...,280.00,42.714286,804.214286,123.071429,0.1530,0.131,0.153,0.153,0.0,0.0
2,2025,Bungoma,591,450,1235,400,20203,7717,30596,8567,...,425.75,36.250000,1358.250000,121.500000,0.0895,0.070,0.085,0.091,0.0,0.0
3,2025,Busia,543,467,940,425,23538,11203,37116,12095,...,425.75,36.250000,1358.250000,121.500000,0.0895,0.070,0.085,0.091,0.0,0.0
4,2025,Elgeyo Marakwet,83,68,149,55,3196,1368,4919,1491,...,280.00,42.714286,804.214286,123.071429,0.1530,0.131,0.153,0.153,0.0,0.0

In [15]:
NSDCC_CLEAN = calculate_yoy_change(
    NSDCC_CLEAN,
    value_col="vls_rate_adult"
)

NSDCC_CLEAN.head()

,period,county,MOH 731_HIV_TB_OnART_15-19_(F)_HV03-24,MOH 731_HIV_TB_OnART_15-19_(M)_HV03-23,MOH 731_HIV_TB_OnART_20-24_(F)_HV03-26,MOH 731_HIV_TB_OnART_20-24_(M)_HV03-25,MOH 731_HIV_TB_OnART_25+_(F)_HV03-28,MOH 731_HIV_TB_OnART_25+_(M)_HV03-27,adults_on_art,art_total_males,...,iit_female,Actively on Treatment by the Beginning of 2025 Male,iit_male,adults_on_treatment,iit_count,iit_rate_pct,iit_rate_children_pct,iit_rate_male_pct,iit_rate_female_pct,vls_rate_adult_yoy_change
0,2025,Baringo,82,70,164,92,3629,1701,5738,1863,...,80.357143,280.00,42.714286,804.214286,123.071429,0.1530,0.131,0.153,0.153,0.0
1,2025,Bomet,234,160,416,175,7745,3616,12346,3951,...,80.357143,280.00,42.714286,804.214286,123.071429,0.1530,0.131,0.153,0.153,0.0
2,2025,Bungoma,591,450,1235,400,20203,7717,30596,8567,...,85.250000,425.75,36.250000,1358.250000,121.500000,0.0895,0.070,0.085,0.091,0.0
3,2025,Busia,543,467,940,425,23538,11203,37116,12095,...,85.250000,425.75,36.250000,1358.250000,121.500000,0.0895,0.070,0.085,0.091,0.0
4,2025,Elgeyo Marakwet,83,68,149,55,3196,1368,4919,1491,...,80.357143,280.00,42.714286,804.214286,123.071429,0.1530,0.131,0.153,0.153,0.0

In [18]:
NSDCC_CLEAN = calculate_care_gap_index(NSDCC_CLEAN)

NSDCC_CLEAN[
    [
        "county",
        "care_gap_index"
    ]
].head()

ValueError: Missing columns for hts positivity calculation

In [ ]:
county_profiles = build_county_profiles(NSDCC_CLEAN)

county_profiles.head()

In [ ]:
plt.figure(figsize=(14, 6))

county_profiles = county_profiles.sort_values(
    "care_gap_index",
    ascending=False
)

plt.bar(
    county_profiles["county"],
    county_profiles["care_gap_index"]
)

plt.xticks(rotation=90)

plt.title(
    "Care Gap Index Across Counties"
)

plt.xlabel("County")

plt.ylabel("Care Gap Index")

plt.tight_layout()

plt.show()